version: '3.8'
services:
  php:
    container_name: ${CONTAINER_PREFIX}todo-list-php
    ports:
        - "${PHP_EXPOSE_PORT}:9000"
    env_file:
      - ./project/.env
    networks:
      - todo-list

  mysql:
    container_name: ${CONTAINER_PREFIX}todo-list-mysql
    ports:
        - "${MYSQL_EXPOSE_PORT}:3306"
    networks:
      - todo-list

  nginx:
    container_name: ${CONTAINER_PREFIX}todo-list-nginx
    ports:
        - "${NGINX_EXPOSE_PORT}:80"
    networks:
      - todo-list

  apidoc:
    container_name: ${CONTAINER_PREFIX}apidoc
    ports:
      - "8089:8080"
    networks:
      - todo-list

networks:
  todo-list: