version: '3.8'
services:
  php:
    build: ./docker/php
    container_name: test-todo-list-php
    restart: always
    volumes:
      - ./project:/var/www/project

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password

    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}

  nginx:
    build: ./docker/nginx
    container_name: test-todo-list-nginx
    restart: always
    volumes:
      - ./project:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
