view_controllers:
    resource: ../../src/Controller/View
    type: annotation

api_controllers:
    resource: ../../src/Controller/Api
    type: annotation
    prefix: /api

kernel:
    resource: ../../src/Kernel.php
    type: annotation
