security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        api:
            pattern: ^/api
            stateless: true
            entry_point: jwt
            json_login:
                check_path: /api/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~
            refresh_jwt:
                check_path: /api/token/refresh

        register:
            pattern: ^/api/register
            stateless: true

        main:
            lazy: true
            provider: app_user_provider
            entry_point: App\Security\AppAuthAuthenticator
            custom_authenticator:
                - App\Security\AppAuthAuthenticator
            logout:
                path: app_logout
            form_login:
                target_path_parameter: app_home

    role_hierarchy:
        ROLE_MANAGER: [ ROLE_USER, ROLE_ALLOW_EDIT, ROLE_ALLOW_CREATE, ROLE_ALLOW_DELETE ]
        ROLE_BAD_PM: [ ROLE_MANAGER ]
        ROLE_ADMIN: [ ROLE_MANAGER ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN ]


    access_control:
        - { path: ^/(login|register), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/(login|token/refresh|doc), roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: [IS_AUTHENTICATED_FULLY, ROLE_USER] }
        - { path: ^/, roles: [IS_AUTHENTICATED_FULLY, ROLE_USER] }
        - { path: ^/, roles: [IS_AUTHENTICATED_FULLY, ROLE_USER] }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
