api_login_check:
  path: /api/login

api_refresh_token:
  path: /api/token/refresh

#Auto redirect to homepage after login / logout
homepage:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /task
    permanent: true